name: Check using py scripts

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Control char test
      run: python CVM/checkfmt.py

    - name: 18 char width test
      run: echo Hello!  # todo

